name: Validation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tslint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install

      - name: Run TSLint
        run: yarn run lint

      - name: Run Test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn run test
